package com.cycapservers.game;

public enum InputAction {
	  WEAPON_1_SELECT, WEAPON_2_SELECT, WEAPON_3_SELECT, WEAPON_4_SELECT, MOVE_UP, MOVE_DOWN, MOVE_LEFT, MOVE_RIGHT, SHOOT, RELOAD, USE_ITEM, ZOOM
}
